// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/messaging/messaging.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	FileUrl       string                 `protobuf:"bytes,7,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileSize      string                 `protobuf:"bytes,8,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileName      string                 `protobuf:"bytes,9,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Message) GetFileSize() string {
	if x != nil {
		return x.FileSize
	}
	return ""
}

func (x *Message) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	FileUrl       string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileSize      string                 `protobuf:"bytes,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileName      string                 `protobuf:"bytes,7,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessageRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SendMessageRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *SendMessageRequest) GetFileSize() string {
	if x != nil {
		return x.FileSize
	}
	return ""
}

func (x *SendMessageRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeleteMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMessageResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// Данные для отдачи файла сообщения через gateway
type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileInfoRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GetFileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	S3Key         string                 `protobuf:"bytes,3,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoResponse) Reset() {
	*x = GetFileInfoResponse{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoResponse) ProtoMessage() {}

func (x *GetFileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoResponse.ProtoReflect.Descriptor instead.
func (*GetFileInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{8}
}

func (x *GetFileInfoResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetFileInfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetFileInfoResponse) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *GetFileInfoResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DeleteChatMsgsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatMsgsRequest) Reset() {
	*x = DeleteChatMsgsRequest{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatMsgsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatMsgsRequest) ProtoMessage() {}

func (x *DeleteChatMsgsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatMsgsRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatMsgsRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteChatMsgsRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type DeleteChatMsgsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatMsgsResponse) Reset() {
	*x = DeleteChatMsgsResponse{}
	mi := &file_proto_messaging_messaging_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatMsgsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatMsgsResponse) ProtoMessage() {}

func (x *DeleteChatMsgsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_messaging_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatMsgsResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatMsgsResponse) Descriptor() ([]byte, []int) {
	return file_proto_messaging_messaging_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteChatMsgsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_messaging_messaging_proto protoreflect.FileDescriptor

const file_proto_messaging_messaging_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/messaging/messaging.proto\x12\tmessaging\"\xeb\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x19\n" +
	"\bfile_url\x18\a \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_size\x18\b \x01(\tR\bfileSize\x12\x1b\n" +
	"\tfile_name\x18\t \x01(\tR\bfileName\"-\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"E\n" +
	"\x13GetMessagesResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.messaging.MessageR\bmessages\"\xc7\x01\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\tR\bfileSize\x12\x1b\n" +
	"\tfile_name\x18\a \x01(\tR\bfileName\"4\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"R\n" +
	"\x14DeleteMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\"0\n" +
	"\x15DeleteMessageResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"3\n" +
	"\x12GetFileInfoRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"v\n" +
	"\x13GetFileInfoResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x15\n" +
	"\x06s3_key\x18\x03 \x01(\tR\x05s3Key\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\"0\n" +
	"\x15DeleteChatMsgsRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"(\n" +
	"\x16DeleteChatMsgsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xab\x03\n" +
	"\x10MessagingService\x12L\n" +
	"\vGetMessages\x12\x1d.messaging.GetMessagesRequest\x1a\x1e.messaging.GetMessagesResponse\x12L\n" +
	"\vSendMessage\x12\x1d.messaging.SendMessageRequest\x1a\x1e.messaging.SendMessageResponse\x12R\n" +
	"\rDeleteMessage\x12\x1f.messaging.DeleteMessageRequest\x1a .messaging.DeleteMessageResponse\x12Y\n" +
	"\x12DeleteChatMessages\x12 .messaging.DeleteChatMsgsRequest\x1a!.messaging.DeleteChatMsgsResponse\x12L\n" +
	"\vGetFileInfo\x12\x1d.messaging.GetFileInfoRequest\x1a\x1e.messaging.GetFileInfoResponseB\x11Z\x0fproto/messagingb\x06proto3"

var (
	file_proto_messaging_messaging_proto_rawDescOnce sync.Once
	file_proto_messaging_messaging_proto_rawDescData []byte
)

func file_proto_messaging_messaging_proto_rawDescGZIP() []byte {
	file_proto_messaging_messaging_proto_rawDescOnce.Do(func() {
		file_proto_messaging_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messaging_messaging_proto_rawDesc), len(file_proto_messaging_messaging_proto_rawDesc)))
	})
	return file_proto_messaging_messaging_proto_rawDescData
}

var file_proto_messaging_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_messaging_messaging_proto_goTypes = []any{
	(*Message)(nil),                // 0: messaging.Message
	(*GetMessagesRequest)(nil),     // 1: messaging.GetMessagesRequest
	(*GetMessagesResponse)(nil),    // 2: messaging.GetMessagesResponse
	(*SendMessageRequest)(nil),     // 3: messaging.SendMessageRequest
	(*SendMessageResponse)(nil),    // 4: messaging.SendMessageResponse
	(*DeleteMessageRequest)(nil),   // 5: messaging.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),  // 6: messaging.DeleteMessageResponse
	(*GetFileInfoRequest)(nil),     // 7: messaging.GetFileInfoRequest
	(*GetFileInfoResponse)(nil),    // 8: messaging.GetFileInfoResponse
	(*DeleteChatMsgsRequest)(nil),  // 9: messaging.DeleteChatMsgsRequest
	(*DeleteChatMsgsResponse)(nil), // 10: messaging.DeleteChatMsgsResponse
}
var file_proto_messaging_messaging_proto_depIdxs = []int32{
	0,  // 0: messaging.GetMessagesResponse.messages:type_name -> messaging.Message
	1,  // 1: messaging.MessagingService.GetMessages:input_type -> messaging.GetMessagesRequest
	3,  // 2: messaging.MessagingService.SendMessage:input_type -> messaging.SendMessageRequest
	5,  // 3: messaging.MessagingService.DeleteMessage:input_type -> messaging.DeleteMessageRequest
	9,  // 4: messaging.MessagingService.DeleteChatMessages:input_type -> messaging.DeleteChatMsgsRequest
	7,  // 5: messaging.MessagingService.GetFileInfo:input_type -> messaging.GetFileInfoRequest
	2,  // 6: messaging.MessagingService.GetMessages:output_type -> messaging.GetMessagesResponse
	4,  // 7: messaging.MessagingService.SendMessage:output_type -> messaging.SendMessageResponse
	6,  // 8: messaging.MessagingService.DeleteMessage:output_type -> messaging.DeleteMessageResponse
	10, // 9: messaging.MessagingService.DeleteChatMessages:output_type -> messaging.DeleteChatMsgsResponse
	8,  // 10: messaging.MessagingService.GetFileInfo:output_type -> messaging.GetFileInfoResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_messaging_messaging_proto_init() }
func file_proto_messaging_messaging_proto_init() {
	if File_proto_messaging_messaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messaging_messaging_proto_rawDesc), len(file_proto_messaging_messaging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_messaging_messaging_proto_goTypes,
		DependencyIndexes: file_proto_messaging_messaging_proto_depIdxs,
		MessageInfos:      file_proto_messaging_messaging_proto_msgTypes,
	}.Build()
	File_proto_messaging_messaging_proto = out.File
	file_proto_messaging_messaging_proto_goTypes = nil
	file_proto_messaging_messaging_proto_depIdxs = nil
}
