// Code generated by protoc-gen-go-grpc. DO NOT EDIT manually.
// To regenerate: protoc --go_out=. --go-grpc_out=. proto/auth/auth.proto

package auth

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ─── Messages ────────────────────────────────────────────────────────────────

type SetCredentialsRequest struct {
	UserId   string
	Password string
}

type SetCredentialsResponse struct {
	Ok bool
}

type LoginRequest struct {
	UserId   string
	Password string
}

type LoginResponse struct {
	Token string
}

type ValidateTokenRequest struct {
	Token string
}

type ValidateTokenResponse struct {
	Valid  bool
	UserId string
}

// ─── Server interface ─────────────────────────────────────────────────────────

type AuthServiceServer interface {
	SetCredentials(context.Context, *SetCredentialsRequest) (*SetCredentialsResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) SetCredentials(context.Context, *SetCredentialsRequest) (*SetCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "SetCredentials not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "Login not implemented")
}
func (UnimplementedAuthServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "ValidateToken not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// ─── Registration ─────────────────────────────────────────────────────────────

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "SetCredentials", Handler: authServiceSetCredentialsHandler},
		{MethodName: "Login", Handler: authServiceLoginHandler},
		{MethodName: "ValidateToken", Handler: authServiceValidateTokenHandler},
	},
	Streams: []grpc.StreamDesc{},
}

func authServiceSetCredentialsHandler(srv any, ctx context.Context, dec func(any) error, _ grpc.UnaryServerInterceptor) (any, error) {
	req := &SetCredentialsRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	return srv.(AuthServiceServer).SetCredentials(ctx, req)
}

func authServiceLoginHandler(srv any, ctx context.Context, dec func(any) error, _ grpc.UnaryServerInterceptor) (any, error) {
	req := &LoginRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	return srv.(AuthServiceServer).Login(ctx, req)
}

func authServiceValidateTokenHandler(srv any, ctx context.Context, dec func(any) error, _ grpc.UnaryServerInterceptor) (any, error) {
	req := &ValidateTokenRequest{}
	if err := dec(req); err != nil {
		return nil, err
	}
	return srv.(AuthServiceServer).ValidateToken(ctx, req)
}

// ─── Client ───────────────────────────────────────────────────────────────────

type AuthServiceClient interface {
	SetCredentials(context.Context, *SetCredentialsRequest, ...grpc.CallOption) (*SetCredentialsResponse, error)
	Login(context.Context, *LoginRequest, ...grpc.CallOption) (*LoginResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest, ...grpc.CallOption) (*ValidateTokenResponse, error)
}

type authServiceClient struct{ cc grpc.ClientConnInterface }

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) SetCredentials(ctx context.Context, req *SetCredentialsRequest, opts ...grpc.CallOption) (*SetCredentialsResponse, error) {
	out := &SetCredentialsResponse{}
	if err := c.cc.Invoke(ctx, "/auth.AuthService/SetCredentials", req, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, req *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := &LoginResponse{}
	if err := c.cc.Invoke(ctx, "/auth.AuthService/Login", req, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidateToken(ctx context.Context, req *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	out := &ValidateTokenResponse{}
	if err := c.cc.Invoke(ctx, "/auth.AuthService/ValidateToken", req, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}
