listening-port=3478
external-ip=84.22.132.243
realm=postly-mes.ru

# Static credentials (lt-cred-mech = long-term credential mechanism)
lt-cred-mech
user=postly:JwHq9pXnKf2RmT7L

# Relay port range — must match docker-compose ports mapping
relay-ports-range=49152-49250

# Disable TLS/DTLS on TURN level (WebRTC uses DTLS-SRTP internally)
no-tls
no-dtls

log-file=/dev/stdout
