// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/s3/s3.proto

package s3pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewS3ClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewS3ClientRequest) Reset() {
	*x = NewS3ClientRequest{}
	mi := &file_proto_s3_s3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewS3ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewS3ClientRequest) ProtoMessage() {}

func (x *NewS3ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_s3_s3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewS3ClientRequest.ProtoReflect.Descriptor instead.
func (*NewS3ClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_s3_s3_proto_rawDescGZIP(), []int{0}
}

type NewS3ClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewS3ClientResponse) Reset() {
	*x = NewS3ClientResponse{}
	mi := &file_proto_s3_s3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewS3ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewS3ClientResponse) ProtoMessage() {}

func (x *NewS3ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_s3_s3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewS3ClientResponse.ProtoReflect.Descriptor instead.
func (*NewS3ClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_s3_s3_proto_rawDescGZIP(), []int{1}
}

type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadFileRequest_FileName
	//	*UploadFileRequest_Chunk
	Data          isUploadFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_proto_s3_s3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_s3_s3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_s3_s3_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFileRequest) GetData() isUploadFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetFileName() string {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_FileName); ok {
			return x.FileName
		}
	}
	return ""
}

func (x *UploadFileRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadFileRequest_Data interface {
	isUploadFileRequest_Data()
}

type UploadFileRequest_FileName struct {
	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3,oneof"` // Например: "avatars/user_123.jpg"
}

type UploadFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadFileRequest_FileName) isUploadFileRequest_Data() {}

func (*UploadFileRequest_Chunk) isUploadFileRequest_Data() {}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S3Key         string                 `protobuf:"bytes,1,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"` // Уникальный путь, под которым файл сохранился в Selectel
	FileUrl       string                 `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_proto_s3_s3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_s3_s3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_s3_s3_proto_rawDescGZIP(), []int{3}
}

func (x *UploadFileResponse) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *UploadFileResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

type GetDownloadUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S3Key         string                 `protobuf:"bytes,1,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`                         // Ключ файла в бакете
	ExpiresInSec  int64                  `protobuf:"varint,2,opt,name=expires_in_sec,json=expiresInSec,proto3" json:"expires_in_sec,omitempty"` // Срок действия ссылки в секундах
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlRequest) Reset() {
	*x = GetDownloadUrlRequest{}
	mi := &file_proto_s3_s3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlRequest) ProtoMessage() {}

func (x *GetDownloadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_s3_s3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_s3_s3_proto_rawDescGZIP(), []int{4}
}

func (x *GetDownloadUrlRequest) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *GetDownloadUrlRequest) GetExpiresInSec() int64 {
	if x != nil {
		return x.ExpiresInSec
	}
	return 0
}

type GetDownloadUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse) Reset() {
	*x = GetDownloadUrlResponse{}
	mi := &file_proto_s3_s3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse) ProtoMessage() {}

func (x *GetDownloadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_s3_s3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_s3_s3_proto_rawDescGZIP(), []int{5}
}

func (x *GetDownloadUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetUploadUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // Оригинальное имя — нужно только для расширения
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ExpiresInSec  int64                  `protobuf:"varint,4,opt,name=expires_in_sec,json=expiresInSec,proto3" json:"expires_in_sec,omitempty"`
	Folder        string                 `protobuf:"bytes,5,opt,name=folder,proto3" json:"folder,omitempty"` // images | videos | voices | files
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadUrlRequest) Reset() {
	*x = GetUploadUrlRequest{}
	mi := &file_proto_s3_s3_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadUrlRequest) ProtoMessage() {}

func (x *GetUploadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_s3_s3_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadUrlRequest.ProtoReflect.Descriptor instead.
func (*GetUploadUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_s3_s3_proto_rawDescGZIP(), []int{6}
}

func (x *GetUploadUrlRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUploadUrlRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetUploadUrlRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetUploadUrlRequest) GetExpiresInSec() int64 {
	if x != nil {
		return x.ExpiresInSec
	}
	return 0
}

func (x *GetUploadUrlRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type GetUploadUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	S3Key         string                 `protobuf:"bytes,2,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadUrlResponse) Reset() {
	*x = GetUploadUrlResponse{}
	mi := &file_proto_s3_s3_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadUrlResponse) ProtoMessage() {}

func (x *GetUploadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_s3_s3_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetUploadUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_s3_s3_proto_rawDescGZIP(), []int{7}
}

func (x *GetUploadUrlResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetUploadUrlResponse) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S3Key         string                 `protobuf:"bytes,1,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_proto_s3_s3_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_s3_s3_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_s3_s3_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFileRequest) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_proto_s3_s3_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_s3_s3_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_s3_s3_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_s3_s3_proto protoreflect.FileDescriptor

const file_proto_s3_s3_proto_rawDesc = "" +
	"\n" +
	"\x11proto/s3/s3.proto\x12\x02s3\"\x14\n" +
	"\x12NewS3ClientRequest\"\x15\n" +
	"\x13NewS3ClientResponse\"R\n" +
	"\x11UploadFileRequest\x12\x1d\n" +
	"\tfile_name\x18\x01 \x01(\tH\x00R\bfileName\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"F\n" +
	"\x12UploadFileResponse\x12\x15\n" +
	"\x06s3_key\x18\x01 \x01(\tR\x05s3Key\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\"T\n" +
	"\x15GetDownloadUrlRequest\x12\x15\n" +
	"\x06s3_key\x18\x01 \x01(\tR\x05s3Key\x12$\n" +
	"\x0eexpires_in_sec\x18\x02 \x01(\x03R\fexpiresInSec\"*\n" +
	"\x16GetDownloadUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xac\x01\n" +
	"\x13GetUploadUrlRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12$\n" +
	"\x0eexpires_in_sec\x18\x04 \x01(\x03R\fexpiresInSec\x12\x16\n" +
	"\x06folder\x18\x05 \x01(\tR\x06folder\"L\n" +
	"\x14GetUploadUrlResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x15\n" +
	"\x06s3_key\x18\x02 \x01(\tR\x05s3Key\"*\n" +
	"\x11DeleteFileRequest\x12\x15\n" +
	"\x06s3_key\x18\x01 \x01(\tR\x05s3Key\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd5\x02\n" +
	"\vFileService\x12=\n" +
	"\n" +
	"UploadFile\x12\x15.s3.UploadFileRequest\x1a\x16.s3.UploadFileResponse(\x01\x12G\n" +
	"\x0eGetDownloadUrl\x12\x19.s3.GetDownloadUrlRequest\x1a\x1a.s3.GetDownloadUrlResponse\x12A\n" +
	"\fGetUploadUrl\x12\x17.s3.GetUploadUrlRequest\x1a\x18.s3.GetUploadUrlResponse\x12;\n" +
	"\n" +
	"DeleteFile\x12\x15.s3.DeleteFileRequest\x1a\x16.s3.DeleteFileResponse\x12>\n" +
	"\vNewS3Client\x12\x16.s3.NewS3ClientRequest\x1a\x17.s3.NewS3ClientResponseB\x1aZ\x18s3-service/proto/s3;s3pbb\x06proto3"

var (
	file_proto_s3_s3_proto_rawDescOnce sync.Once
	file_proto_s3_s3_proto_rawDescData []byte
)

func file_proto_s3_s3_proto_rawDescGZIP() []byte {
	file_proto_s3_s3_proto_rawDescOnce.Do(func() {
		file_proto_s3_s3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_s3_s3_proto_rawDesc), len(file_proto_s3_s3_proto_rawDesc)))
	})
	return file_proto_s3_s3_proto_rawDescData
}

var file_proto_s3_s3_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_s3_s3_proto_goTypes = []any{
	(*NewS3ClientRequest)(nil),     // 0: s3.NewS3ClientRequest
	(*NewS3ClientResponse)(nil),    // 1: s3.NewS3ClientResponse
	(*UploadFileRequest)(nil),      // 2: s3.UploadFileRequest
	(*UploadFileResponse)(nil),     // 3: s3.UploadFileResponse
	(*GetDownloadUrlRequest)(nil),  // 4: s3.GetDownloadUrlRequest
	(*GetDownloadUrlResponse)(nil), // 5: s3.GetDownloadUrlResponse
	(*GetUploadUrlRequest)(nil),    // 6: s3.GetUploadUrlRequest
	(*GetUploadUrlResponse)(nil),   // 7: s3.GetUploadUrlResponse
	(*DeleteFileRequest)(nil),      // 8: s3.DeleteFileRequest
	(*DeleteFileResponse)(nil),     // 9: s3.DeleteFileResponse
}
var file_proto_s3_s3_proto_depIdxs = []int32{
	2, // 0: s3.FileService.UploadFile:input_type -> s3.UploadFileRequest
	4, // 1: s3.FileService.GetDownloadUrl:input_type -> s3.GetDownloadUrlRequest
	6, // 2: s3.FileService.GetUploadUrl:input_type -> s3.GetUploadUrlRequest
	8, // 3: s3.FileService.DeleteFile:input_type -> s3.DeleteFileRequest
	0, // 4: s3.FileService.NewS3Client:input_type -> s3.NewS3ClientRequest
	3, // 5: s3.FileService.UploadFile:output_type -> s3.UploadFileResponse
	5, // 6: s3.FileService.GetDownloadUrl:output_type -> s3.GetDownloadUrlResponse
	7, // 7: s3.FileService.GetUploadUrl:output_type -> s3.GetUploadUrlResponse
	9, // 8: s3.FileService.DeleteFile:output_type -> s3.DeleteFileResponse
	1, // 9: s3.FileService.NewS3Client:output_type -> s3.NewS3ClientResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_s3_s3_proto_init() }
func file_proto_s3_s3_proto_init() {
	if File_proto_s3_s3_proto != nil {
		return
	}
	file_proto_s3_s3_proto_msgTypes[2].OneofWrappers = []any{
		(*UploadFileRequest_FileName)(nil),
		(*UploadFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_s3_s3_proto_rawDesc), len(file_proto_s3_s3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_s3_s3_proto_goTypes,
		DependencyIndexes: file_proto_s3_s3_proto_depIdxs,
		MessageInfos:      file_proto_s3_s3_proto_msgTypes,
	}.Build()
	File_proto_s3_s3_proto = out.File
	file_proto_s3_s3_proto_goTypes = nil
	file_proto_s3_s3_proto_depIdxs = nil
}
