// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/friends/friends.proto

package friends

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_proto_friends_friends_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_friends_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_friends_friends_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FriendRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *FriendRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_proto_friends_friends_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_friends_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_proto_friends_friends_proto_rawDescGZIP(), []int{1}
}

func (x *Friend) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SendFriendRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestReq) Reset() {
	*x = SendFriendRequestReq{}
	mi := &file_proto_friends_friends_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestReq) ProtoMessage() {}

func (x *SendFriendRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_friends_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestReq.ProtoReflect.Descriptor instead.
func (*SendFriendRequestReq) Descriptor() ([]byte, []int) {
	return file_proto_friends_friends_proto_rawDescGZIP(), []int{2}
}

func (x *SendFriendRequestReq) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendFriendRequestReq) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

type SendFriendRequestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResp) Reset() {
	*x = SendFriendRequestResp{}
	mi := &file_proto_friends_friends_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResp) ProtoMessage() {}

func (x *SendFriendRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_friends_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResp.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResp) Descriptor() ([]byte, []int) {
	return file_proto_friends_friends_proto_rawDescGZIP(), []int{3}
}

func (x *SendFriendRequestResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SendFriendRequestResp) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

type GetFriendRequestsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendRequestsReq) Reset() {
	*x = GetFriendRequestsReq{}
	mi := &file_proto_friends_friends_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendRequestsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendRequestsReq) ProtoMessage() {}

func (x *GetFriendRequestsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_friends_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendRequestsReq.ProtoReflect.Descriptor instead.
func (*GetFriendRequestsReq) Descriptor() ([]byte, []int) {
	return file_proto_friends_friends_proto_rawDescGZIP(), []int{4}
}

func (x *GetFriendRequestsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFriendRequestsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendRequestsResp) Reset() {
	*x = GetFriendRequestsResp{}
	mi := &file_proto_friends_friends_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendRequestsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendRequestsResp) ProtoMessage() {}

func (x *GetFriendRequestsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_friends_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendRequestsResp.ProtoReflect.Descriptor instead.
func (*GetFriendRequestsResp) Descriptor() ([]byte, []int) {
	return file_proto_friends_friends_proto_rawDescGZIP(), []int{5}
}

func (x *GetFriendRequestsResp) GetRequests() []*FriendRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type AcceptFriendRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestReq) Reset() {
	*x = AcceptFriendRequestReq{}
	mi := &file_proto_friends_friends_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestReq) ProtoMessage() {}

func (x *AcceptFriendRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_friends_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestReq.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestReq) Descriptor() ([]byte, []int) {
	return file_proto_friends_friends_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptFriendRequestReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AcceptFriendRequestReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AcceptFriendRequestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestResp) Reset() {
	*x = AcceptFriendRequestResp{}
	mi := &file_proto_friends_friends_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestResp) ProtoMessage() {}

func (x *AcceptFriendRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_friends_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestResp.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestResp) Descriptor() ([]byte, []int) {
	return file_proto_friends_friends_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptFriendRequestResp) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type DeclineFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendReq) Reset() {
	*x = DeclineFriendReq{}
	mi := &file_proto_friends_friends_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendReq) ProtoMessage() {}

func (x *DeclineFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_friends_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendReq.ProtoReflect.Descriptor instead.
func (*DeclineFriendReq) Descriptor() ([]byte, []int) {
	return file_proto_friends_friends_proto_rawDescGZIP(), []int{8}
}

func (x *DeclineFriendReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeclineFriendReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type DeclineFriendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendResp) Reset() {
	*x = DeclineFriendResp{}
	mi := &file_proto_friends_friends_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendResp) ProtoMessage() {}

func (x *DeclineFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_friends_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendResp.ProtoReflect.Descriptor instead.
func (*DeclineFriendResp) Descriptor() ([]byte, []int) {
	return file_proto_friends_friends_proto_rawDescGZIP(), []int{9}
}

func (x *DeclineFriendResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetFriendsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsReq) Reset() {
	*x = GetFriendsReq{}
	mi := &file_proto_friends_friends_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsReq) ProtoMessage() {}

func (x *GetFriendsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_friends_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsReq.ProtoReflect.Descriptor instead.
func (*GetFriendsReq) Descriptor() ([]byte, []int) {
	return file_proto_friends_friends_proto_rawDescGZIP(), []int{10}
}

func (x *GetFriendsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFriendsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*Friend              `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsResp) Reset() {
	*x = GetFriendsResp{}
	mi := &file_proto_friends_friends_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsResp) ProtoMessage() {}

func (x *GetFriendsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_friends_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsResp.ProtoReflect.Descriptor instead.
func (*GetFriendsResp) Descriptor() ([]byte, []int) {
	return file_proto_friends_friends_proto_rawDescGZIP(), []int{11}
}

func (x *GetFriendsResp) GetFriends() []*Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

var File_proto_friends_friends_proto protoreflect.FileDescriptor

const file_proto_friends_friends_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/friends/friends.proto\x12\afriends\"[\n" +
	"\rFriendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"!\n" +
	"\x06Friend\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"T\n" +
	"\x14SendFriendRequestReq\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\"W\n" +
	"\x15SendFriendRequestResp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\"/\n" +
	"\x14GetFriendRequestsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"K\n" +
	"\x15GetFriendRequestsResp\x122\n" +
	"\brequests\x18\x01 \x03(\v2\x16.friends.FriendRequestR\brequests\"P\n" +
	"\x16AcceptFriendRequestReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"6\n" +
	"\x17AcceptFriendRequestResp\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\"J\n" +
	"\x10DeclineFriendReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"#\n" +
	"\x11DeclineFriendResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"(\n" +
	"\rGetFriendsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x0eGetFriendsResp\x12)\n" +
	"\afriends\x18\x01 \x03(\v2\x0f.friends.FriendR\afriends2\xa0\x03\n" +
	"\x0eFriendsService\x12R\n" +
	"\x11SendFriendRequest\x12\x1d.friends.SendFriendRequestReq\x1a\x1e.friends.SendFriendRequestResp\x12R\n" +
	"\x11GetFriendRequests\x12\x1d.friends.GetFriendRequestsReq\x1a\x1e.friends.GetFriendRequestsResp\x12X\n" +
	"\x13AcceptFriendRequest\x12\x1f.friends.AcceptFriendRequestReq\x1a .friends.AcceptFriendRequestResp\x12M\n" +
	"\x14DeclineFriendRequest\x12\x19.friends.DeclineFriendReq\x1a\x1a.friends.DeclineFriendResp\x12=\n" +
	"\n" +
	"GetFriends\x12\x16.friends.GetFriendsReq\x1a\x17.friends.GetFriendsRespB\x0fZ\rproto/friendsb\x06proto3"

var (
	file_proto_friends_friends_proto_rawDescOnce sync.Once
	file_proto_friends_friends_proto_rawDescData []byte
)

func file_proto_friends_friends_proto_rawDescGZIP() []byte {
	file_proto_friends_friends_proto_rawDescOnce.Do(func() {
		file_proto_friends_friends_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_friends_friends_proto_rawDesc), len(file_proto_friends_friends_proto_rawDesc)))
	})
	return file_proto_friends_friends_proto_rawDescData
}

var file_proto_friends_friends_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_friends_friends_proto_goTypes = []any{
	(*FriendRequest)(nil),           // 0: friends.FriendRequest
	(*Friend)(nil),                  // 1: friends.Friend
	(*SendFriendRequestReq)(nil),    // 2: friends.SendFriendRequestReq
	(*SendFriendRequestResp)(nil),   // 3: friends.SendFriendRequestResp
	(*GetFriendRequestsReq)(nil),    // 4: friends.GetFriendRequestsReq
	(*GetFriendRequestsResp)(nil),   // 5: friends.GetFriendRequestsResp
	(*AcceptFriendRequestReq)(nil),  // 6: friends.AcceptFriendRequestReq
	(*AcceptFriendRequestResp)(nil), // 7: friends.AcceptFriendRequestResp
	(*DeclineFriendReq)(nil),        // 8: friends.DeclineFriendReq
	(*DeclineFriendResp)(nil),       // 9: friends.DeclineFriendResp
	(*GetFriendsReq)(nil),           // 10: friends.GetFriendsReq
	(*GetFriendsResp)(nil),          // 11: friends.GetFriendsResp
}
var file_proto_friends_friends_proto_depIdxs = []int32{
	0,  // 0: friends.GetFriendRequestsResp.requests:type_name -> friends.FriendRequest
	1,  // 1: friends.GetFriendsResp.friends:type_name -> friends.Friend
	2,  // 2: friends.FriendsService.SendFriendRequest:input_type -> friends.SendFriendRequestReq
	4,  // 3: friends.FriendsService.GetFriendRequests:input_type -> friends.GetFriendRequestsReq
	6,  // 4: friends.FriendsService.AcceptFriendRequest:input_type -> friends.AcceptFriendRequestReq
	8,  // 5: friends.FriendsService.DeclineFriendRequest:input_type -> friends.DeclineFriendReq
	10, // 6: friends.FriendsService.GetFriends:input_type -> friends.GetFriendsReq
	3,  // 7: friends.FriendsService.SendFriendRequest:output_type -> friends.SendFriendRequestResp
	5,  // 8: friends.FriendsService.GetFriendRequests:output_type -> friends.GetFriendRequestsResp
	7,  // 9: friends.FriendsService.AcceptFriendRequest:output_type -> friends.AcceptFriendRequestResp
	9,  // 10: friends.FriendsService.DeclineFriendRequest:output_type -> friends.DeclineFriendResp
	11, // 11: friends.FriendsService.GetFriends:output_type -> friends.GetFriendsResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_friends_friends_proto_init() }
func file_proto_friends_friends_proto_init() {
	if File_proto_friends_friends_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_friends_friends_proto_rawDesc), len(file_proto_friends_friends_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_friends_friends_proto_goTypes,
		DependencyIndexes: file_proto_friends_friends_proto_depIdxs,
		MessageInfos:      file_proto_friends_friends_proto_msgTypes,
	}.Build()
	File_proto_friends_friends_proto = out.File
	file_proto_friends_friends_proto_goTypes = nil
	file_proto_friends_friends_proto_depIdxs = nil
}
